# version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 2s
      timeout: 3s
      retries: 15

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://app:app@db:5432/appdb
      - SECRET_KEY=devsecretdemo
      - DEMO_USERNAME=admin
      - DEMO_PASSWORD=demopass
      - LLM_ENABLED=true
      - LLM_MODEL=deepseek/deepseek-chat-v3.1:free
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
volumes:
  pgdata:
